#!/bin/bash
echo "=== 验证 GitHub Pages 部署 ==="
echo ""

echo "1. 检查 GitHub Pages 设置:"
echo "   访问: https://github.com/planarcat/blog/settings/pages"
echo "   应该显示:"
echo "   - Source: GitHub Actions"
echo "   - 环境: github-pages"
echo "   - 状态: Your site is live at https://planarcat.github.io/blog"
echo ""
echo "2. 检查部署历史:"
echo "   访问: https://github.com/planarcat/blog/deployments"
echo "   查看最近的部署，点击查看详情"
echo ""
echo "3. 手动触发重新部署:"
echo "   如果需要，可以在 GitHub Actions 页面手动触发 workflow_dispatch"
echo "   访问: https://github.com/planarcat/blog/actions"
echo "   点击 'Deploy Blog'，然后 'Run workflow'"
echo ""
echo "4. 清除 GitHub Pages 缓存:"
echo "   由于 GitHub Pages 使用 CDN，可能有缓存。"
echo "   尝试以下方法清除缓存:"
echo "   a. 访问 https://planarcat.github.io/blog?t=\$(date +%s)"
echo "   b. 使用 curl 带 no-cache 头:"
echo "      curl -H 'Cache-Control: no-cache' https://planarcat.github.io/blog"
echo ""
echo "5. 检查实际部署的文件:"
echo "   访问以下链接查看实际部署的文件:"
echo "   - https://planarcat.github.io/blog/ (应该看到博客)"
echo "   - https://planarcat.github.io/blog/test.html (测试页面，如果部署了)"
echo "   - https://planarcat.github.io/blog/css/main.css (CSS 文件)"
echo "   - https://planarcat.github.io/blog/js/main.js (JS 文件)"
